# coding: utf-8

import os

PCL_REST_API_USER_ID = os.environ.get('PCL_REST_API_USER_ID', '')
PCL_REST_API_CLIENT_SECRET = os.environ.get('PCL_REST_API_CLIENT_SECRET', '')
PCL_REST_API_CLIENT_ID = os.environ.get('PCL_REST_API_CLIENT_ID', '')
PCL_REST_API_SUBSCRIPTION_PRIMARY_KEY = os.environ.get('PCL_REST_API_SUBSCRIPTION_PRIMARY_KEY', '')
PCL_APIG_CLIENT_ORIGINATOR = os.environ.get('PCL_APIG_CLIENT_ORIGINATOR', '')
PCL_APIG_CLIENT_CHANNEL = os.environ.get('PCL_APIG_CLIENT_CHANNEL', '')
PCL_APIG_CLIENT_CHANNEL_VERSION = os.environ.get('PCL_APIG_CLIENT_CHANNEL_VERSION', '')
PCL_APIG_REQUEST_UID = os.environ.get('PCL_APIG_REQUEST_UID', '')
PCL_REST_API_VERSION = os.environ.get('PCL_REST_API_VERSION', '')
PCL_REST_API_CLIENT_NAME = os.environ.get('PCL_REST_API_CLIENT_NAME', '')
