version: "3.8"

services:
  mock_pcl_rest_api:
    build:
      context: ../
      dockerfile: docker/Dockerfile
      target: mock_pcl_rest_api
    volumes:
      - ./:/srv/mock
    command: python --host=0.0.0.0 app.py
